name: Supabase Functions Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use the LTS version of Node.js
      - name: Install dependencies
        run: npm install
      - name: Deploy Supabase Functions
        run: ./deploy_supabase_functions.sh
      - name: Check Deployment Status
        run: echo "Deployment successful!"
