  
   name: Supabase Functions Deploy

   on:
     push:
       branches: [ main ]
       paths:
         - 'supabase/functions/**'

   jobs:
     deploy-functions:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - run: ./deploy_supabase_functions.sh 