   name: TypeScript Type Checking

   on: [push, pull_request]

   jobs:
     type-check:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: Use Node.js
           uses: actions/setup-node@v1
           with:
             node-version: '18.x'
         - run: npm install
         - run: npm run type-check